### ISSUE TITLE
Excepciones necesarias

### ISSUE THREAD

**Issue by jrenteria003** [jrenteria003/taco.bell#18]
Se me ocurre que necesitariamos las siguientes excepciones:

- Usuarie no existe
- Producto no existe
- Error de ejecucion
- Error al cargar los datos
- Error de conexon con la base de datos

Si se os ocurre alguna otra podeis añadir aquí porfa?

**Comment by optickx** [comment]
Longitud de el texto excesiva (mayor que la fijada en la base de datos).

**Comment by jrenteria003** [comment]
cierro issue ya que el proyecto esta terminado
