### ISSUE TITLE
Ventanas

### ISSUE THREAD

**Issue by jrenteria003** [jrenteria003/taco.bell#19]
los layouts de todas las ventanas estan ya terminados; queda implementar codigo para rellenar los productos y demas datos y hacer que funcionen todas en conjunto

**Comment by jrenteria003** [comment]
nico empieza con la ventana de VLogin (controlar el login) y yo me empiezo con las JTable de VPedido

**Comment by jrenteria003** [comment]
la clase Producto requiere ser modificada, ya que no se refleja el tipo de producto, necesario para filtrar segun producto en el menu del pedido

**Comment by jrenteria003** [comment]
### Queda crear las ventanas ###

- VRegister <- Basada en VLogin
- VDatos <- Basada en VGestion

**Comment by NicoRodBilbao** [comment]
VLogin es prácticamente perfecta, a excepción de:

- No consigo que el focus no se dirija al correo electrónico, haciéndolo bastante difícil de utilizar.
- El botón de registrarse aún no está implementado

**Comment by jrenteria003** [comment]
el boton de registrase no iba a ser el texto de abajo? o hace falta alguno mas?

**Comment by jrenteria003** [comment]
Queda lo siguiente en VRegister:

- Boton indicando que se acepan los terminos
- Apellido

**Comment by jrenteria003** [comment]
@NicoRodBilbao la ventana de gestion para trabajadores solo deberia mostrar los pedidos asociados a su establecimiento, deshabilitando el resto de botones

**Comment by optickx** [comment]
Lo veo bastante bien.

**Comment by jrenteria003** [comment]
cierro issue ya que el proyecto esta terminado
